version: '3.1'

services:
  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - '9088:9088'
    networks:
      - net

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - '9087:9087'
    networks:
      - net

networks:
  net:
    driver: bridge