spring:
  datasource:
    url: jdbc:h2:file:./exploDb;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: user
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: payment
server:
  port: 8083
  error:
    include-message: always
    include-stacktrace: on-param
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
