spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/explorMaghrebDB
      auto-index-creation: true
  application:
    name: ReviewService
server:
  port: 8084
  error:
    include-message: always
    include-stacktrace: on-param
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
