
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  error:
    include-message: always
    include-stacktrace: on-param
  port: 8088
spring:
  cloud:
     config:
        enabled: false
  application:
    name: guide-service
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/explorMaghrebDB
